{"name": "test_get_wiki_page_by_path_logs_error", "status": "passed", "description": "Test logger called when extraction fails due to an API error.", "start": 1743505056242, "stop": 1743505056242, "uuid": "e386e9b4-2895-4499-95ab-b26d8f00515b", "historyId": "bc8ee579e4f4f84c70629c747354bfa4", "testCaseId": "bc8ee579e4f4f84c70629c747354bfa4", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_get_wiki_page_by_path_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}