{"name": "test_run_with_tool_that_raises_exception", "status": "passed", "description": "Test that `run` handles tools that raise exceptions.", "start": 1743499571490, "stop": 1743499571490, "uuid": "77f2db40-39e4-45da-910f-68318fb9dd86", "historyId": "51f4c5721ca4ccb62a2babd807338dfb", "testCaseId": "51f4c5721ca4ccb62a2babd807338dfb", "fullName": "src.tests.test_elitea_base_tool.TestBaseToolApiWrapper#test_run_with_tool_that_raises_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "base"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_elitea_base_tool"}, {"name": "subSuite", "value": "TestBaseToolApiWrapper"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_elitea_base_tool"}]}