{"name": "test_create_test_suite_exception", "status": "passed", "description": "Test create test suite logger exception.", "start": 1743499569975, "stop": 1743499569976, "uuid": "de5d33da-e822-494b-8165-23fd7a03b6c8", "historyId": "72cf47816e339f4e7204ff0c5661f4a1", "testCaseId": "72cf47816e339f4e7204ff0c5661f4a1", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_create_test_suite_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}