{"name": "test_rename_wiki_page_logs_error", "status": "passed", "description": "Test logger called when rename fails due to an API error.", "start": 1743501667653, "stop": 1743501667655, "uuid": "ed36d464-b6bc-4189-b19b-a8f35cba342d", "historyId": "71729a1fe2a260f2c0a93ad24ba88d3e", "testCaseId": "71729a1fe2a260f2c0a93ad24ba88d3e", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_rename_wiki_page_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}