{"name": "test_create_branch_existing_exception", "status": "passed", "attachments": [{"name": "log", "source": "2a5036e3-98c2-4563-9f5f-b18ec30d6107-attachment.txt", "type": "text/plain"}], "start": 1743499569471, "stop": 1743499569472, "uuid": "7895cf77-0d2d-41e5-84c8-b17f9015df47", "historyId": "c7f4a6c9424eaa6e9f5f4e0b8c2529a6", "testCaseId": "c7f4a6c9424eaa6e9f5f4e0b8c2529a6", "fullName": "src.tests.ado.repos.test_unit_ado_repos.TestReposToolsExceptions#test_create_branch_existing_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_repos"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.repos"}, {"name": "suite", "value": "test_unit_ado_repos"}, {"name": "subSuite", "value": "TestReposToolsExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.repos.test_unit_ado_repos"}]}