{"name": "test_delete_page_by_id_logs_error", "status": "passed", "description": "Test logger called when deletion fails due to an API error.", "start": 1743505056303, "stop": 1743505056304, "uuid": "083eb334-7802-4554-a4de-aa83cacbce15", "historyId": "e767c70782f301ed5af712c5f5aa0876", "testCaseId": "e767c70782f301ed5af712c5f5aa0876", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_delete_page_by_id_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}