{"name": "test_delete_page_by_path_logs_error", "status": "passed", "description": "Test logger called when deletion fails due to an API error.", "start": 1743505056282, "stop": 1743505056283, "uuid": "ee382c33-2b8f-4172-964a-e5dc76bef0bb", "historyId": "aa4dacec8f32b34bbe237fa052e00cbf", "testCaseId": "aa4dacec8f32b34bbe237fa052e00cbf", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_delete_page_by_path_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}