{"name": "test_delete_page_by_path_logs_error", "status": "passed", "description": "Test logger called when deletion fails due to an API error.", "start": 1743504727851, "stop": 1743504727852, "uuid": "1778fe4e-5373-44b4-9f67-eb2136b2e597", "historyId": "aa4dacec8f32b34bbe237fa052e00cbf", "testCaseId": "aa4dacec8f32b34bbe237fa052e00cbf", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_delete_page_by_path_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}