{"name": "test_get_wiki_logs_error", "status": "passed", "description": "Test logger called when extraction fails due to an API error.", "start": 1743501667549, "stop": 1743501667550, "uuid": "6e46d93b-3852-467d-8678-3700a742b528", "historyId": "c359d071fa4f5790e87c777e4c43f977", "testCaseId": "c359d071fa4f5790e87c777e4c43f977", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_get_wiki_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}