{"name": "test_run_unknown_mode", "status": "passed", "description": "Test that `run` raises exception for unknown mode.", "start": 1743505056556, "stop": 1743505056556, "uuid": "90426f30-de06-4c1a-85ef-1cf163d5e04f", "historyId": "0ec6623439e8322689fe9d3ebd59a756", "testCaseId": "0ec6623439e8322689fe9d3ebd59a756", "fullName": "src.tests.test_elitea_base_tool.TestBaseToolApiWrapper#test_run_unknown_mode", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "base"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_elitea_base_tool"}, {"name": "subSuite", "value": "TestBaseToolApiWrapper"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_elitea_base_tool"}]}