{"name": "test_run_unknown_mode", "status": "passed", "description": "Test that `run` raises exception for unknown mode.", "start": 1743504728125, "stop": 1743504728125, "uuid": "54c4449a-6128-4a1f-a240-76e72d257121", "historyId": "0ec6623439e8322689fe9d3ebd59a756", "testCaseId": "0ec6623439e8322689fe9d3ebd59a756", "fullName": "src.tests.test_elitea_base_tool.TestBaseToolApiWrapper#test_run_unknown_mode", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "base"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_elitea_base_tool"}, {"name": "subSuite", "value": "TestBaseToolApiWrapper"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_elitea_base_tool"}]}