{"name": "test_get_all_test_suites_logs_error", "status": "passed", "description": "Test logger called when retrieval of all test suites fails.", "start": 1743501666430, "stop": 1743501666431, "uuid": "74a9369a-b5b7-499c-882d-510ed0e20101", "historyId": "668eb79671db0515f0d48793ef24a536", "testCaseId": "668eb79671db0515f0d48793ef24a536", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_all_test_suites_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}